name: Deploy Cloudflare Webhook

on:
  workflow_dispatch:

nobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set Secrets
        run: |
          wrangler secret put GITHUB_TOKEN --env production --non-interactive --value="${{ secrets.GITHUB_TOKEN }}"
          wrangler secret put GITHUB_WEBHOOK_SECRET --env production --non-interactive --value="${{ secrets.GITHUB_WEBHOOK_SECRET }}"
      - name: Publish Worker
        run: wrangler publish --env production