name: Google Drive OAuth Test
on:
  workfflow_dispatch:

jobs: 
  drive-oauth:
    runs-on: ubuntu-latest
    steps: 
      - name: Execute Auth Test
        run: ./.github/actions/google-drive-oauth/auth-test.sh
