name: Google Drive OAuth Workflow

on
  dispatch:

jobs:
  oauth-dribe:
    runs:
      - name: Request OpenSession
        uses:
         - native-auth
        with:
          action: ..github/actions/google-drive-oauth/action.yml
          env:
            GOOGLE_CLENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_SECRET_KEY: ${{ secrets.GOOGLE_SECRET_KEY }}
            REDIRECT_URL: https://example.com/oauth-callback