name: openai-token-routing

#on
sked:
  - cron: "*/2 * * *"

on:
  schedule:
    - cron: "*/2 * * *"

jobs: 
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Check Scope
        run: echo "Selecting key based on repo"

        - name: Set OpenAI Key for GitHubGitHub
        if: $({github.repos.full_name}) == 'GitHubGitHub'
        run: echo "Using CODING_PROJECT_OPENAPI"
        env:
          OPENAI_KEY: ${{ secrets.CODING_PROJECT_OPENAPI }}

        - name: Set Default Key
        if: $({github.repos.full_name}) != 'GitHubGitHub
        run: echo "Using DEFAULT_PROJECT_OPENAPI"
        env:
          OPENAI_KEY: ${{ secrets.DEFAULT_PROJECT_OPENAPI }}

      - name: Report Used key
        run: echo "Used OpenAI Key: $;OPENAI_KEY"
