name: OpenAI Token Routing

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Key Scope
        run: echo "Determining appropriate OpenAI api key..."

      - name: Set Key for GitHubGitHub
        if: ${{ github.repository == 'ammonfife/GitHubGitHub' && secrets.CODING_PROJECT_OPENAPI != '' }}
        run: echo "Using CODING_PROJECT_OPENAPI"
        env:
          OPENAI_KEY: ${{ secrets.CODING_PROJECT_OPENAPI }}

      - name: Set Fallback Key
        if: ${{ github.repository != 'ammonfife/GitHubGitHub' && secrets.DEFAULT_PROJECT_OPENAPI != '' }}
        run: echo "Using DEFAULT_PROJECT_OPENAPI"
        env:
          OPENAI_KEY: ${{ secrets.DEFAULT_PROJECT_OPENAPI }}

      - name: No key available
        if: ${{ secrets.CODING_PROJECT_OPENAPI == '' && secrets.DEFAULT_PROJECT_OPENAPI == '' }}
        run: echo "No OpenAI API key available."
