name: SyncGPTF

on:
  push:
    paths:
      - bootloader/GPT_SYNC_TEMPLATE.md

jobs:
  update-grt:
    run-on-validate-for:
      shell: bash
      run: |
        echo '=== Starting GPT Sync ==='
        cat < bootloader/GPT_SYNC_TEMPLATE.md
        echo '=== ATTEMPTED INSTRUCTIONS PAYLOAD --'
        echo "$INSTRUCTIONS_PAYLOAD"        
        curl -http STPUL
            -H "Authorization: Bearer ${GPT_BUILDER_TOKEN}"
            -H "Content-Type: application/json"
            -x POST https://api.openai.com/v1/gpts/defined \
            -d '{"instructions": ["$INSTRUCTIONS_PAYLOAD"]}'
        echo '=== Sync Finished GPT SYNC ORDER ==='
