name: Test Repository Secrets

on:
  workflow_dispatch:

jobs: 
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Test CLOUDFLARE_API_TOKEN
      run: curl -s -o /dev/null -w "%{http_code}" -X GET
        -h "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" https://api.cloudflare.com/client/v4/user/tokens/verify
    - name: Test GHA_ADMIN_OPENAI_KEY
      run: curl -s -o /dev/null -w "%{http_code}" https://api.openai.com/v1/models -H Authorization: Bearer {{ secrets.GHA_ADMIN_OPENAI_KEY }}
    - name: Test GITH_ADMIN
      run: curl -s -o /dev/null -w "%{http_code}" -H Authorization: token {{ secrets.GITH_ADMIN }} https://api.github.com/user
    - name: Test GPT_BUILDER_TOKEN
      run: curl -s -o /dev/null -w "%{http_code}" -H Authorization: Bearer {{ secrets.GPT_BUILDER_TOKEN }} https://api.openai.com/v1/models
    - name: Test GROK_API
      run: curl -s -o /dev/null -w "%{http_code}" https://api.grok.com/v1/ping
        -- -H Authorization: Bearer {{ secrets.GROK_API }}
